# Generated by Django 5.1.7 on 2025-04-09 03:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snacks', 'Snacks')], max_length=20)),
                ('calories_per_unit', models.FloatField(help_text='Calories per gram or per unit')),
            ],
        ),
        migrations.CreateModel(
            name='MealEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(help_text='Quantity in grams or number')),
                ('quantity_type', models.CharField(choices=[('grams', 'Grams'), ('number', 'Number')], max_length=10)),
                ('date_time', models.DateTimeField()),
                ('total_calories', models.FloatField(editable=False, help_text='Total calories for this meal entry')),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mealcalorie_app.fooditem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
